activation: silu
aggr: add
atom_filter: -1
attn_activation: silu
batch_size: 128
charge: false
conf: null
coord_files: null
cutoff_lower: 0.0
cutoff_upper: 10.0
dataset: HDF5
dataset_arg: null
dataset_root: SPICE-processed.hdf5
derivative: true
distance_influence: both
distributed_backend: ddp
early_stopping_patience: 20
ema_alpha_dy: 1.0
ema_alpha_y: 1.0
embed_files: null
embedding_dimension: 128
energy_files: null
energy_weight: 1.0
force_files: null
force_weight: 1.0
inference_batch_size: 128
load_model: null
log_dir: model1b
lr: 0.0005
lr_factor: 0.5
lr_metric: train_loss
lr_min: 1.0e-07
lr_patience: 0
lr_warmup_steps: 0
max_num_neighbors: 100
max_z: 28
model: equivariant-transformer
neighbor_embedding: true
ngpus: -1
num_epochs: 1000
num_heads: 8
num_layers: 6
num_nodes: 1
num_rbf: 64
num_workers: 16
output_model: Scalar
precision: 32
prior_model: null
rbf_type: expnorm
redirect: true
reduce_op: add
reset_trainer: false
save_interval: 1
seed: 1
spin: false
splits: null
standardize: false
test_interval: 10
test_size: 0.0
train_size: null
trainable_rbf: true
val_size: 0.05
weight_decay: 0.0
